# Generated by Django 3.1.7 on 2021-04-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squarrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Longititude')),
                ('y', models.FloatField(help_text='Latitude')),
                ('unique_squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=32)),
                ('hectare', models.CharField(help_text='Hectare', max_length=32)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Time of day', max_length=32)),
                ('date', models.CharField(help_text='Date', max_length=32)),
                ('age', models.CharField(choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult')], help_text='Age of squarrel', max_length=32)),
                ('primary_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='primary fur color', max_length=32)),
                ('highlight_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='highlight fur color', max_length=32)),
                ('location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='location', max_length=32)),
                ('specific_location', models.CharField(help_text='Specific location', max_length=32)),
                ('running', models.BooleanField(help_text='Running')),
                ('chasing', models.BooleanField(help_text='Chasing')),
                ('climbing', models.BooleanField(help_text='Climbing')),
                ('eating', models.BooleanField(help_text='Eating')),
                ('foraging', models.BooleanField(help_text='Foraging')),
                ('other_activities', models.CharField(help_text='other_activities', max_length=32)),
                ('kuks', models.BooleanField(help_text='kuks')),
                ('quaas', models.BooleanField(help_text='quaas')),
                ('moans', models.BooleanField(help_text='moans')),
                ('tail_flags', models.BooleanField(help_text='tail_flags')),
                ('tail_twitches', models.BooleanField(help_text='tail_twitches')),
                ('approaches', models.BooleanField(help_text='approaches')),
                ('indifferent', models.BooleanField(help_text='indifferent')),
                ('runs_from', models.BooleanField(help_text='runs_from')),
            ],
        ),
    ]
