# Generated by Django 3.1.7 on 2021-04-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squarrel',
            name='approaches',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='chasing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='climbing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='eating',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='foraging',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='indifferent',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='kuks',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='moans',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='quaas',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='running',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='runs_from',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='tail_flags',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='tail_twitches',
            field=models.BooleanField(),
        ),
    ]
