# Generated by Django 3.1.7 on 2021-04-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20210402_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squarrel',
            name='other_activities',
            field=models.CharField(max_length=32),
        ),
    ]
