# Generated by Django 3.1.7 on 2021-04-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_auto_20210402_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squarrel',
            old_name='other_activities',
            new_name='other_interactions',
        ),
    ]
