# Generated by Django 3.1.7 on 2021-04-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_auto_20210402_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squarrel',
            name='other_interactions',
        ),
        migrations.AddField(
            model_name='squarrel',
            name='other_activities',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
