# Generated by Django 3.1.7 on 2021-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_auto_20210402_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='squarrel',
            name='other_interactions',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='other_activities',
            field=models.CharField(max_length=32),
        ),
    ]
