# Generated by Django 3.1.7 on 2021-04-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_auto_20210402_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squarrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squarrel',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=32, primary_key=True, serialize=False),
        ),
    ]
