# Generated by Django 3.1.7 on 2021-04-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0007_auto_20210402_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('x', models.FloatField(help_text='Longititude')),
                ('y', models.FloatField(help_text='Latitude')),
                ('unique_squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=32, primary_key=True, serialize=False)),
                ('hectare', models.CharField(help_text='Hectare', max_length=32)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Time of day', max_length=32)),
                ('date', models.CharField(help_text='Date', max_length=32)),
                ('age', models.CharField(choices=[('Juvenile', 'Juvenile'), ('Adult', 'Adult')], help_text='Age of squirrel', max_length=32)),
                ('primary_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='primary fur color', max_length=32)),
                ('highlight_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='highlight fur color', max_length=32)),
                ('location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='location', max_length=32)),
                ('specific_location', models.CharField(help_text='Specific location', max_length=32)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('other_activities', models.CharField(max_length=32)),
                ('kuks', models.BooleanField()),
                ('quaas', models.BooleanField()),
                ('moans', models.BooleanField()),
                ('tail_flags', models.BooleanField()),
                ('tail_twitches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runs_from', models.BooleanField()),
                ('other_interactions', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Squarrel',
        ),
    ]
